### ISSUE TITLE
Create Text Based UI viewing tracked flights

### ISSUE THREAD

**Issue by Blarfnip** [TimMarotta/swengflight#21]

**Comment by JoshHayden** [comment]
Worked for around 2 ours getting basic UI set up and writing scripts, can't really do specific test without knowing how our database works just yet.

**Comment by JoshHayden** [comment]
Worked for about half an hour setting up landing page

**Comment by JoshHayden** [comment]
Worked for around 3 hours making the viewing page work, ran into some issues with user input but eventually fixed
