### ISSUE TITLE
Investigate Live API

### ISSUE THREAD

**Issue by timothymarotta** [TimMarotta/swengflight#44]
How To Demo:
- Discussion about API usage
- Goal: possible recommendation/tests to show connection?

**Comment by Blarfnip** [comment]
API code is in place. We now have access to a LOT of data. I tried to make it as efficient as possible. It saves and caches all previous requests. We need to discuss how we want to restructure the rest of our codebase to fit this new dataset.

**Comment by Blarfnip** [comment]
This is technically done but will spawn off a bunch of cards for the next sprint.
