### ISSUE TITLE
Create User Class

### ISSUE THREAD

**Issue by JoshHayden** [TimMarotta/swengflight#7]
Worked for about an hour and half, basic functionality of User up and running now

**Comment by JoshHayden** [comment]
Worked for about half an hour building stubs, pushed for now so User class and stubs are in master, but can't develop other methods until Trip is written

**Comment by gabepesco** [comment]
Should be good on the new branch, if it's mostly good then we can move it to master.

**Comment by JoshHayden** [comment]
Worked fr about an hour and a half, basic User up and running now

**Comment by gabepesco** [comment]
Looks good to me, all tests passing on my machine and has good equivalence partitions.
